### ISSUE TITLE
plugin is not listing all R versions

### ISSUE THREAD

**Issue by rinkjames** [asdf-community/asdf-r#5]
`asdf latest R` shows v4.1.0, but:

<img width="737" alt="Screenshot 2021-08-04 at 12 19 57" src="https://user-images.githubusercontent.com/13288151/128165107-c436321e-f5e0-4768-9b3b-80f2b37571d7.png">

**Comment by smorimoto** [comment]
Thank you for the report @rinkjames! It's already fixed in the latest main channel, so just update the plugin!
